apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{ cookiecutter.name }}
  description: Simple Node.js Hello World service
spec:
  type: service
  lifecycle: experimental
  owner: platform-team
